steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'APP_VERSION=$_VERSION', '-t', 'gcr.io/$PROJECT_ID/cbk-image-service-compress:$_VERSION', '-f', 'Dockerfile.compress', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cbk-image-service-compress:$_VERSION']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'cbk-image-service-compress'  # <-- 这里是你要部署的服务的名称
  - '--image'
  - 'gcr.io/$PROJECT_ID/cbk-image-service-compress:$_VERSION'
  - '--region'
  - 'asia-east1'
  - '--platform'
  - 'managed'
options:
  logging: CLOUD_LOGGING_ONLY  # 指定 Cloud Build 只使用 Cloud Logging 记录日志
substitutions:
  _VERSION: '1.0.0' # <-- 你可以在这里设置默认的版本号
