name: Deploy to Google Cloud Run

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore cbk.project.cloudUploadImage.sln
    

  deploy:
    needs: build
    runs-on: ubuntu-latest    
    steps:   
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
            TAG_NAME=${GITHUB_REF#refs/tags/}
            VERSION=$(echo $TAG_NAME | grep -o '[0-9]\+[.][0-9]\+[.][0-9]\+$')
            
            declare -A SERVICES=( ["member"]="cloudbuild-service-member.yaml" ["upload"]="cloudbuild-service-upload.yaml" ["compress"]="cloudbuild-service-compress.yaml" )

            for KEY in ${!SERVICES[@]}; do
              if [[ "${TAG_NAME}" == *"$KEY"* ]]; then
                YAML_FILE=${SERVICES[$KEY]}
                gcloud builds submit --config ${YAML_FILE} --substitutions _VERSION=${VERSION} .
              fi
            done
