name: ci
  
on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore cbk.project.cloudUploadImage.sln
    

  deploy:
    needs: build        
    steps:
    
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
            TAG_NAME=${GITHUB_REF#refs/tags/}
            if [[ "${TAG_NAME}" == "member"* ]]; then
               YAML_FILE=cloudbuild-member-service.yaml
            elif [[ "${TAG_NAME}" == "upload"* ]]; then
               YAML_FILE=cloudbuild-upload-service.yaml
            elif [[ "${TAG_NAME}" == "compress"* ]]; then
               YAML_FILE=cloudbuild-compress-service.yaml
            else
               YAML_FILE=cloudbuild-member-service.yaml
            fi
            gcloud builds submit --config ${YAML_FILE} .